### ISSUE TITLE
Recycling Initiative Cap Assumed

### ISSUE THREAD

**Issue by Kasikil** [RandomNoobster/Autolycus#7]
Currently when using the "/builds" command the bot incorrectly assumes a nation can have four recycling centers instead 3. Change the default to 3 and update the following if statement to also update the default recycling center limit to 4.

if nation['recycling_initiative'] == True:

Cool bot though, thanks!

**Comment by RandomNoobster** [comment]
I believe the same goes for hospitals and police stations as a consequence of the Clinical Research Center and the Specialized Police Training Program.
